git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    # https://github.com/jesseduffield/lazygit/blob/fadc2893d21c798e2b64b7f7929927347cf242dd/docs/Custom_Pagers.md?plain=1#L70
    # externalDiffCommand: difft --color=always
# os:
# Allow opening in neovim process that launched lazygit
# editPreset: nvim-remote
gui:
  # Enable nerd fonts
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
