[language-server.lexical]
command = "/Users/blakedietz/projects/lexical-lsp/lexical/_build/dev/package/lexical/bin/start_lexical.sh"

[[language]]
name = "elixir"
language-servers = ["lexical", "elixir-ls"]

[[language]]
name = "heex"
language-servers = ["lexical", "elixir-ls"]
